### PR TITLE
Aarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #28 
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
What does `error: unknown type name 'uintn'; did you mean 'uint'?` mean?

**Comment by hmaarrfk** [comment]
seems like it is some custom defined datatypes by the hdf group

https://github.com/cedadev/jasmin_scivm/blob/master/SOURCES/hdf-4.2.4-s390.patch

**Comment by hmaarrfk** [comment]
I think the tests are failing on ppc64le due to some memory stuff.

Running linux locally on my machine made my comptuer basically halt for 60 seconds during the test section.

**Comment by hmaarrfk** [comment]
nice drone got triggered. time to see if these bugs are real, are just qemu related.

**Comment by hmaarrfk** [comment]
It seems that HDF4 didn't have the correct settings or tests for ppc64le 

```
>>> External value 57 was expecting 57 got 956301312
```

is basically

```python
In [3]: hex(956301312)                                                                                   
Out[3]: '0x39000000'

In [4]: hex(57)                                                                                          
Out[4]: '0x39'
```

Should we care about fixing this?

This seems out of scope for conda-forge, and out of scope for hdf4 (Seeing as hdf5 now exists)

**Comment by hmaarrfk** [comment]
it seems debian did a good job packaging these for ppc64le and aarch64

https://salsa.debian.org/debian-gis-team/hdf4/-/tree/master/debian%2Fpatches

I wonder if there is a way to upstream these patches.

**Comment by gillins** [comment]
@hmaarrfk can we assume that `hdf4` isn't going to run on `aarch64` etc easily...?

**Comment by hmaarrfk** [comment]
We've skipped it as a dependency in an other package. hdf5 only on alternative architectures.

**Comment by matthiasdiener** [comment]
Aarch support has been added via #36.

**Pull request closed without merging**
